name: musicalization

publish_to: 'none'

version: 1.1.2+7

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  realm: ^3.1.0
  audioplayers: ^6.0.0
  flutter_riverpod: ^2.5.1
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  image_picker: ^1.1.2
  path: ^1.9.0
  youtube_explode_dart: ^2.3.10
  file_picker: ^9.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/mp3_menu_auto_sound_control.png
    - assets/images/mp3_menu_lyrics_setting.png
    - assets/images/mp3_menu_name_change_button.png
    - assets/images/mp3_menu_picture_setting.png
    - assets/images/mp3_mode_main.png
    - assets/images/mp3_mode_list.png
    - assets/images/mp3_mode_music.png
    - assets/images/mp3_mode_setting.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mp3_app_icon.png"
